# Generated by Django 6.0.7 on 2026-07-28 14:22

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_latitude', models.FloatField(default=12.9715987, help_text='Campus Center Latitude')),
                ('center_longitude', models.FloatField(default=77.5945627, help_text='Campus Center Longitude')),
                ('radius_meters', models.FloatField(default=500.0, help_text='Allowed Radius in Meters')),
                ('college_start_time', models.TimeField(default=datetime.time(9, 0), help_text='College Opening Time (09:00 AM)')),
                ('college_end_time', models.TimeField(default=datetime.time(16, 0), help_text='College Closing Time (04:00 PM)')),
            ],
            options={
                'verbose_name': 'Campus Configuration',
                'verbose_name_plural': 'Campus Configurations',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department Name (e.g. Computer Science)', max_length=100, unique=True)),
                ('email', models.EmailField(help_text='Department HOD or Admin Email for Early Exit Alerts', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Email OTP Log',
                'verbose_name_plural': 'Email OTP Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(help_text='Unique Roll Number', max_length=50, unique=True)),
                ('face_bytes', models.BinaryField(blank=True, help_text='Binary LBPH Face Encoding / Image Feature Vector', null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='attendance.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['roll_number'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('entry_time', models.TimeField(blank=True, null=True)),
                ('exit_time', models.TimeField(blank=True, null=True)),
                ('entry_lat', models.FloatField(blank=True, null=True)),
                ('entry_lon', models.FloatField(blank=True, null=True)),
                ('exit_lat', models.FloatField(blank=True, null=True)),
                ('exit_lon', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, help_text='Face recognition confidence score', null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('LEFT_EARLY', 'Left Early')], default='PRESENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.student')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', '-entry_time'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
